config/routes.rb
Rails.application.routes.draw do
  root to: "polls#active"
  
  devise_for :users
  
  get 'polls/active', as: :active_polls
  get 'polls/completed', as: :completed_polls
    
  resources :polls, only: [:new, :create, :show]
  resources :votes, only: :create
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    can [:active, :completed, :complete, :show], Poll
    
    if user.instructor?
      can [:new, :create], Poll
    end
  end
end

app/models/poll.rb
# == Schema Information
#
# Table name: polls
#
#  id         :integer          not null, primary key
#  question   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  active     :boolean          default("true")
#

class Poll < ActiveRecord::Base
  acts_as_taggable
  
  has_many :responses
  has_many :votes, through: :responses
  
  accepts_nested_attributes_for :responses, reject_if: proc { |attr| attr['content'].blank? }
  
  validates :question, presence: true
  validates :responses, presence: true
  
  def close!
    self.update_attribute(:active, false)
  end
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  poll_id    :integer
#  content    :string
#  correct    :boolean          default("false")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Response < ActiveRecord::Base
  belongs_to :poll
  
  has_many :votes
  
  validates :content, presence: true
  
  def is_correct!
    self.update_attribute(:correct, true)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  instructor             :boolean          default("false")
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
  
  def has_voted_on?(poll)
    poll.votes.where(user: self).any?
  end
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  response_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :response
  
  delegate :poll, to: :response
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!
  
  load_and_authorize_resource
  
  def new
    @poll = Poll.new
    @poll.responses.build
  end
  
  def create    
    @poll = Poll.new(poll_params)
    @poll.tag_list.map! &:downcase
    
    if @poll.save
      redirect_to @poll
    else
      flash.now[:alert] = @poll.errors.full_messages.to_sentence
      @poll.responses.build
      render :new
    end
  end
  
  def show
    if current_user.has_voted_on?(@poll) || !@poll.active?
      @poll = Poll.includes(responses: :votes).find(params[:id])
      
      @responses = @poll.responses.sort_by do |x| 
        [ -x.votes.size, x.correct? ? 1 : 0 ]
      end
      
      @vote_count = @responses.map(&:votes).map(&:to_a).flatten.count
      
      render :results
    else
      @poll = Poll.includes(:responses).find(params[:id])
      @responses = @poll.responses.shuffle
      @vote = Vote.new
      
      render :vote
    end
  end
  
  def active
    @polls = Poll.where(active: true)
  end
  
  def completed
    @polls = Poll.where(active: false)
  end
  
  private
  
  def poll_params
    params.require(:poll).permit( :question, :tag_list, responses_attributes: [:content] )
  end  
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @response = Response.find(vote_params[:response_id])
    @poll = @response.poll
    
    if current_user.instructor?
      @poll.close!
      @response.is_correct!
    else
      @vote = Vote.new(user: current_user, response: @response)
      @vote.save
    end
    
    redirect_to @poll
  end
  
  private
  
  def vote_params
    params.require(:vote).permit(:response_id)
  end
end


# def complete
#   @poll = Poll.includes(:responses).find(params[:id])
#   @chosen_response = Response.find(params[:response_id])
#
#   if current_user.instructor?
#     @poll.close!(@chosen_response)
#   else
#     @vote = Vote.new(user: current_user, response: @chosen_response)
#   end
#
#   redirect_to completed_polls_url
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snappy Polls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="clearfix">
    <span class="pull-left">
      Snappy Polls
    </span>
    
    <ul class="pull-right">
      <% if current_user && current_user.instructor?%>
        <li>
          <%= link_to "Make A Poll", new_poll_url %>
        </li>
      <% end %>
      <li>
        <%= link_to "Active Polls", active_polls_url %>
      </li>
      <li>
        <%= link_to "Completed Polls", completed_polls_url %>
      </li>
      <% if current_user %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_url, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_user_session_url %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_url %>
        </li>      
      <% end %>
    </ul>
  </header>
  
  <section class="notifications">
    <% if notice %>
      <p class="notice">
        <%= notice %>
      </p>
    <% end %>
    <% if alert %>
      <p class="alert">
        <%= alert %>
      </p>
    <% end %>
  </section>
  
  <main>
    <%= yield %>
  </main>

</body>
</html>

app/views/polls/_index.html.erb
<% @polls.each do |poll| %>
  <%= link_to poll, class: 'button full-width' do %>
    <%= poll.question %> <small class="vote-count"> <%= pluralize poll.votes.count, "vote" %></small>
  <% end %>
<% end %>

app/views/polls/active.html.erb
<section class="polls">
  <h1>Active Polls</h1>
  <%= render partial: 'index', locals: { polls: @polls } %>
</section>

app/views/polls/complete.html.erb
<h1>
  <%= @poll.question %>
</h1>

<%= form_for @vote do |v| %>
  <fieldset class="vote">
    <% @poll.responses.each do |response| %>
      <%= v.radio_button :response_id, response.id %>
      <%= v.label :response_id, response.content, value: response.id, class: "button full-width" %>
    <% end %>
  </fieldset>
<% end %>

<script>
  $('form').on('change', function(event) {
    $(this).submit();
  })
</script>

app/views/polls/completed.html.erb
<section class="polls">
  <h1>Completed Polls</h1>
  <%= render partial: 'index', locals: { polls: @polls } %>
</section>

app/views/polls/new.html.erb
<%= form_for @poll, html: { autocomplete: "off" } do |p| %>
  <fieldset class="question">
    <%= p.label :question %>
    <%= p.text_field :question, autofocus: true %>
  </fieldset>
  
  <fieldset class="tags">
    <%= p.label :tag_list, "Topics (seperated by commas)" %>
    <%= p.text_field :tag_list %>
  </fieldset>
  
  <%= p.fields_for :responses do |a| %>
    <div class="responses">
      <fieldset class="response">
        <%= a.label :content, "Response" %>
        <%= a.text_field :content %>
      </fieldset>
    </div>
  <% end %>
  
  <%= button_tag('Create Poll', type: 'submit') %>
<% end %>

<script>
  $('form').on('keypress', '.response:last-child input', function(event) {    
    if (event.charCode != 13) {
      var $template = $(this).parent();
      var templateId = $template.find('input').attr('name').match(/\d+/);
    
      var $nextResponse = $template.clone().css('display', 'none');
    
      var $nextLabel = $nextResponse.find('label');
      var $nextInput = $nextResponse.find('input');
      var nextId = (parseInt(templateId) + 1).toString()

      $nextLabel.attr( 'for', $nextLabel.attr('for').replace(templateId, nextId) );
    
      $nextInput.val('');
      $nextInput.attr( 'name', $nextInput.attr('name').replace(templateId, nextId) );
      $nextInput.attr( 'id', $nextInput.attr('id').replace(templateId, nextId) );
    
      $('.responses').append($nextResponse);
      $nextResponse.slideDown();
    };
  });
</script>

app/views/polls/results.html.erb
<% if @poll.active? %>
  <h1>
    Poll is still being voted on...
  </h1>
<% else %>
  <h1>
    Poll is over, here are the results...
  </h1>
  
  <section class="results">
    <h2>
      <%= @poll.question %>
      <% if @poll.tag_list.any? %>
        <small class="tag-list">
          [Tags: <%= @poll.tag_list. join(', ') %>]
        </small>
      <% end %>
    </h2>
    
    <% @responses.each do |response| %>
      <% response_count = response.votes.count %>
      <% percent = (@vote_count == 0 ? 0 : (100 * response_count) / @vote_count) %>
    
        <div class="result <%= "correct" if response.correct %>">
          <div class="response clearfix">
            <span class="pull-left">
              <%= response.content %> 
              
            </span>
            <span class="pull-right">
              <small>[<%= pluralize response_count, "student" %>]</small>
              <% if response.correct %>
                <i class="fa fa-birthday-cake"></i>      
              <% end %>
            </span>
          </div>
          
          <div class="strength" data-percent="<%= percent %>">
          </div>
        </div>
    <% end %>
  </section>
<% end %>

<script>
  var colors = ['orange', 'blue', 'green', 'yellow', 'black', 'purple']

  $('div.strength').each(function(i) {
    var $div = $(this);
    $div.css('background', colors[i]);
    
    var percent = $div.data('percent');
    $div.animate({
      width: percent + "%"
    }, 1000);
  })
</script>

app/views/polls/show.html.erb
<% if @poll.active? %>
  <h1>
    Poll is still being voted on...
  </h1>
<% else %>
  <h1>
    Poll is over, here are the results...
  </h1>
  
  <section class="results">
    <h2>
      <%= @poll.question %>
    </h2>
    
    <% @responses.each do |response| %>
      <% response_count = response.votes.count %>
      <% percent = (@vote_count == 0 ? 0 : (100 * response_count) / @vote_count) %>
    
        <div class="result <%= "correct" if response.correct %>">
          <div class="response clearfix">
            <span class="pull-left">
              <%= response.content %> 
              
            </span>
            <span class="pull-right">
              <small>[<%= pluralize response_count, "student" %>]</small>
              <% if response.correct %>
                <i class="fa fa-birthday-cake"></i>      
              <% end %>
            </span>
          </div>
          
          <div class="strength" data-percent="<%= percent %>">
          </div>
        </div>
    <% end %>
  </section>
<% end %>

<script>
  var colors = ['orange', 'blue', 'green', 'yellow', 'black', 'purple']

  $('div.strength').each(function(i) {
    var $div = $(this);
    $div.css('background', colors[i]);
    
    var percent = $div.data('percent');
    $div.animate({
      width: percent + "%"
    }, 'slow')
  })
</script>

app/views/polls/vote.html.erb
<h1>
  <%= @poll.question %>
</h1>

<%= form_for @vote do |v| %>
  <fieldset class="vote">
    <% @poll.responses.each do |response| %>
      <%= v.radio_button :response_id, response.id %>
      <%= v.label :response_id, response.content, value: response.id, class: "button full-width" %>
    <% end %>
  </fieldset>
<% end %>

<script>
  $('form').on('change', function(event) {
    $(this).submit();
  })
</script>